# PROJECT 2 : GRAPH ALGORITHMS

#### TEAM MEMBERS  :  TANVI RASAM, CHAITANYA DARADE

# Source Code For Dijkstra's Algorithm Implementation Using Array

In [1]:
import sys 
from IPython.core.debugger import set_trace
  
class Graph(): 
  
    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [[0 for column in range(vertices)]  
                      for row in range(vertices)] 
  
    def printPath(self, src, parent, j): 
        #Base Case : If j is source 
        if parent[j] == 999:
            if src == j:
                print(chr(j+65)," ",end = ''),
            else:
                print("UNREACHABLE",end = ''),
            return
        self.printPath(src, parent , parent[j]) 
        print(chr(j+65)," ",end = ''),
  
    def printSolution(self, src, dist, parent):
        print("Vertex \t\tDistance from Source\t\t\t  Path")
        for node in range(0,self.V): 
            print("\n%s --> %s \t\t%d \t\t\t\t" % (chr(src+65), chr(node+65), dist[node])," ", end = ''),
            self.printPath(src,parent,node)
            
    # A utility function to find the vertex with  
    # minimum distance value, from the set of vertices  
    # not yet included in shortest path tree 
    def minDistance(self, dist, sptSet):
        min_index = -1
        
        # Initilaize minimum distance for next node 
        min = sys.maxsize 
        
        # Search not nearest vertex not in the  
        # shortest path tree 
        for v in range(self.V): 
            if dist[v] < min and sptSet[v] == False: 
                min = dist[v] 
                min_index = v 
                     
        return min_index

    # Funtion that implements Dijkstra's single source  
    # shortest path algorithm for a graph represented  
    # using adjacency matrix representation 
    def dijkstra(self, src):
        src = ord(src.upper())-65
        dist = [sys.maxsize] * self.V 
        parent = [999] * self.V
        dist[src] = 0
        sptSet = [False] * self.V 
  
        parent[src] = 999 # First node is always the root of
        for cout in range(self.V): 
  
            # Pick the minimum distance vertex from  
            # the set of vertices not yet processed.  
            # u is always equal to src in first iteration 
            u = self.minDistance(dist, sptSet) 
              
            if(u==-1):
                break
            # Put the minimum distance vertex in the  
            # shotest path tree 
            sptSet[u] = True
  
            # Update dist value of the adjacent vertices  
            # of the picked vertex only if the current  
            # distance is greater than new distance and 
            # the vertex in not in the shotest path tree 
            for v in range(self.V): 
                if self.graph[u][v] > 0 and sptSet[v] == False and dist[v] > dist[u] + self.graph[u][v]: 
                    dist[v] = dist[u] + self.graph[u][v] 
                    parent[v] = u
  
        self.printSolution(src,dist,parent)

# Reading Input File-1(Directed) and Creating Adjacency Matrix

In [2]:
file = open("Input_File_Dir_0.rtf", 'r')

In [3]:
Dir_graph = 0
lines = file.readlines()
list1 = lines[0].split()
if list1[2] == 'D':
    Dir_graph = 1

In [4]:
g_size = lines[0][0].split()
print(int(lines[0][0].split()[0]))

9


In [5]:
import numpy as np

g_size = int(lines[0][0].split()[0])
g = Graph(g_size)

g.graph = np.zeros((g_size,g_size))

print(g.graph)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
if Dir_graph == 1:
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
else :
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
        g.graph[ord(j.upper())-65][ord(i.upper())-65]=val

In [7]:
print(g.graph)

[[0. 1. 2. 0. 4. 0. 0. 0. 0.]
 [0. 0. 1. 3. 2. 0. 0. 0. 0.]
 [0. 0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 4. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 5. 0. 4.]
 [0. 0. 0. 0. 0. 0. 0. 4. 6.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Call Dijkstra's Algorithm from Source Node 'A', 'B', 'C'

In [8]:
g.dijkstra('A');

Vertex 		Distance from Source			  Path

A --> A 		0 				  A  
A --> B 		1 				  A  B  
A --> C 		2 				  A  C  
A --> D 		3 				  A  C  D  
A --> E 		3 				  A  B  E  
A --> F 		6 				  A  C  D  F  
A --> G 		11 				  A  C  D  F  G  
A --> H 		15 				  A  C  D  F  G  H  
A --> I 		10 				  A  C  D  F  I  

In [9]:
g.dijkstra('B');

Vertex 		Distance from Source			  Path

B --> A 		9223372036854775807 				  UNREACHABLE
B --> B 		0 				  B  
B --> C 		1 				  B  C  
B --> D 		2 				  B  C  D  
B --> E 		2 				  B  E  
B --> F 		5 				  B  C  D  F  
B --> G 		10 				  B  C  D  F  G  
B --> H 		14 				  B  C  D  F  G  H  
B --> I 		9 				  B  C  D  F  I  

In [10]:
g.dijkstra('C');

Vertex 		Distance from Source			  Path

C --> A 		9223372036854775807 				  UNREACHABLE
C --> B 		9223372036854775807 				  UNREACHABLE
C --> C 		0 				  C  
C --> D 		1 				  C  D  
C --> E 		2 				  C  E  
C --> F 		4 				  C  D  F  
C --> G 		9 				  C  D  F  G  
C --> H 		13 				  C  D  F  G  H  
C --> I 		8 				  C  D  F  I  

# Reading Input File-1(UnDirected) and Creating Adjacency Matrix 

In [11]:
file = open("Input_File_UnDir_0.rtf", 'r')

In [12]:
Dir_graph = 0
lines = file.readlines()
list1 = lines[0].split()
if list1[2] == 'D':
    Dir_graph = 1

In [13]:
g_size = lines[0][0].split()
print(int(lines[0][0].split()[0]))

9


In [14]:
import numpy as np

g_size = int(lines[0][0].split()[0])
g = Graph(g_size)

g.graph = np.zeros((g_size,g_size))

print(g.graph)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
if Dir_graph == 1:
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
else :
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
        g.graph[ord(j.upper())-65][ord(i.upper())-65]=val

In [16]:
print(g.graph)

[[0. 1. 2. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 3. 2. 0. 0. 0. 0.]
 [2. 1. 0. 1. 2. 0. 0. 0. 0.]
 [0. 3. 1. 0. 4. 3. 0. 0. 0.]
 [0. 2. 2. 4. 0. 3. 0. 0. 0.]
 [0. 0. 0. 3. 3. 0. 5. 0. 4.]
 [0. 0. 0. 0. 0. 5. 0. 4. 6.]
 [0. 0. 0. 0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 0. 4. 6. 0. 0.]]


# Call Dijkstra's Algorithm from Source Node 'A', 'B', 'C'

In [17]:
g.dijkstra('A');

Vertex 		Distance from Source			  Path

A --> A 		0 				  A  
A --> B 		1 				  A  B  
A --> C 		2 				  A  C  
A --> D 		3 				  A  C  D  
A --> E 		3 				  A  B  E  
A --> F 		6 				  A  C  D  F  
A --> G 		11 				  A  C  D  F  G  
A --> H 		15 				  A  C  D  F  G  H  
A --> I 		10 				  A  C  D  F  I  

In [18]:
g.dijkstra('B');

Vertex 		Distance from Source			  Path

B --> A 		1 				  B  A  
B --> B 		0 				  B  
B --> C 		1 				  B  C  
B --> D 		2 				  B  C  D  
B --> E 		2 				  B  E  
B --> F 		5 				  B  C  D  F  
B --> G 		10 				  B  C  D  F  G  
B --> H 		14 				  B  C  D  F  G  H  
B --> I 		9 				  B  C  D  F  I  

In [19]:
g.dijkstra('C');

Vertex 		Distance from Source			  Path

C --> A 		2 				  C  A  
C --> B 		1 				  C  B  
C --> C 		0 				  C  
C --> D 		1 				  C  D  
C --> E 		2 				  C  E  
C --> F 		4 				  C  D  F  
C --> G 		9 				  C  D  F  G  
C --> H 		13 				  C  D  F  G  H  
C --> I 		8 				  C  D  F  I  

# Reading Input File-2(Directed) and Creating Adjacency Matrix

In [20]:
file = open("Input_File_Dir_1.rtf", 'r')

In [21]:
Dir_graph = 0
lines = file.readlines()
list1 = lines[0].split()
if list1[2] == 'D':
    Dir_graph = 1

In [22]:
g_size = lines[0][0].split()
print(int(lines[0][0].split()[0]))

8


In [23]:
import numpy as np

g_size = int(lines[0][0].split()[0])
g = Graph(g_size)

g.graph = np.zeros((g_size,g_size))

print(g.graph)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [24]:
if Dir_graph == 1:
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
else :
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
        g.graph[ord(j.upper())-65][ord(i.upper())-65]=val

In [25]:
print(g.graph)

[[ 0.  4.  3.  0.  7.  0.  0.  0.]
 [ 0.  0.  6.  5.  0. 15.  0.  0.]
 [ 0.  0.  0. 11.  8.  0.  0.  0.]
 [ 0.  0.  0.  0.  2.  2. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  5. 20.]
 [ 0.  0.  0.  0.  0.  0.  3.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 10.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


# Call Dijkstra's Algorithm from Source Node 'A', 'C', 'E'

In [26]:
g.dijkstra('A');

Vertex 		Distance from Source			  Path

A --> A 		0 				  A  
A --> B 		4 				  A  B  
A --> C 		3 				  A  C  
A --> D 		9 				  A  B  D  
A --> E 		7 				  A  E  
A --> F 		11 				  A  B  D  F  
A --> G 		12 				  A  E  G  
A --> H 		22 				  A  E  G  H  

In [27]:
g.dijkstra('C');

Vertex 		Distance from Source			  Path

C --> A 		9223372036854775807 				  UNREACHABLE
C --> B 		9223372036854775807 				  UNREACHABLE
C --> C 		0 				  C  
C --> D 		11 				  C  D  
C --> E 		8 				  C  E  
C --> F 		13 				  C  D  F  
C --> G 		13 				  C  E  G  
C --> H 		23 				  C  E  G  H  

In [28]:
g.dijkstra('E');

Vertex 		Distance from Source			  Path

E --> A 		9223372036854775807 				  UNREACHABLE
E --> B 		9223372036854775807 				  UNREACHABLE
E --> C 		9223372036854775807 				  UNREACHABLE
E --> D 		9223372036854775807 				  UNREACHABLE
E --> E 		0 				  E  
E --> F 		9223372036854775807 				  UNREACHABLE
E --> G 		5 				  E  G  
E --> H 		15 				  E  G  H  

# Reading Input File-2(UnDirected) and Creating Adjacency Matrix

In [29]:
file = open("Input_File_UnDir_1.rtf", 'r')

In [30]:
Dir_graph = 0
lines = file.readlines()
list1 = lines[0].split()
if list1[2] == 'D':
    Dir_graph = 1

In [31]:
g_size = lines[0][0].split()
print(int(lines[0][0].split()[0]))

7


In [32]:
import numpy as np

g_size = int(lines[0][0].split()[0])
g = Graph(g_size)

g.graph = np.zeros((g_size,g_size))

print(g.graph)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [33]:
if Dir_graph == 1:
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
else :
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
        g.graph[ord(j.upper())-65][ord(i.upper())-65]=val

In [34]:
print(g.graph)

[[ 0.  4.  3.  0.  7.  0.  0.]
 [ 4.  0.  6.  5.  0.  0.  0.]
 [ 3.  6.  0. 11.  8.  0.  0.]
 [ 0.  5. 11.  0.  2.  2. 10.]
 [ 7.  0.  8.  2.  0.  0.  5.]
 [ 0.  0.  0.  2.  0.  0.  3.]
 [ 0.  0.  0. 10.  5.  3.  0.]]


## Call Dijkstra's Algorithm from Source Node 'A', 'C', 'E'

In [35]:
g.dijkstra('A');

Vertex 		Distance from Source			  Path

A --> A 		0 				  A  
A --> B 		4 				  A  B  
A --> C 		3 				  A  C  
A --> D 		9 				  A  B  D  
A --> E 		7 				  A  E  
A --> F 		11 				  A  B  D  F  
A --> G 		12 				  A  E  G  

In [36]:
g.dijkstra('C');

Vertex 		Distance from Source			  Path

C --> A 		3 				  C  A  
C --> B 		6 				  C  B  
C --> C 		0 				  C  
C --> D 		10 				  C  E  D  
C --> E 		8 				  C  E  
C --> F 		12 				  C  E  D  F  
C --> G 		13 				  C  E  G  

In [37]:
g.dijkstra('E');

Vertex 		Distance from Source			  Path

E --> A 		7 				  E  A  
E --> B 		7 				  E  D  B  
E --> C 		8 				  E  C  
E --> D 		2 				  E  D  
E --> E 		0 				  E  
E --> F 		4 				  E  D  F  
E --> G 		5 				  E  G  

# Reading Input File-3(Directed) and Creating Adjacency Matrix

In [38]:
file = open("Input_File_Dir_2.rtf", 'r')

In [39]:
Dir_graph = 0
lines = file.readlines()
list1 = lines[0].split()
if list1[2] == 'D':
    Dir_graph = 1

In [40]:
g_size = lines[0][0].split()
print(int(lines[0][0].split()[0]))

9


In [41]:
import numpy as np

g_size = int(lines[0][0].split()[0])
g = Graph(g_size)

g.graph = np.zeros((g_size,g_size))

print(g.graph)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [42]:
if Dir_graph == 1:
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
else :
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
        g.graph[ord(j.upper())-65][ord(i.upper())-65]=val

In [43]:
print(g.graph)

[[ 0.  4.  0.  0.  0.  0.  0.  8.  0.]
 [ 0.  0.  8.  0.  0.  0.  0. 11.  0.]
 [ 0.  0.  0.  7.  0.  4.  0.  0.  2.]
 [ 0.  0.  0.  0.  9. 14. 16.  0.  0.]
 [ 0.  0.  0.  0.  0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  6.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  7.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


# Call Dijkstra's Algorithm from Source Node 'A', 'D', 'F'

In [44]:
g.dijkstra('A');

Vertex 		Distance from Source			  Path

A --> A 		0 				  A  
A --> B 		4 				  A  B  
A --> C 		12 				  A  B  C  
A --> D 		19 				  A  B  C  D  
A --> E 		28 				  A  B  C  D  E  
A --> F 		16 				  A  B  C  F  
A --> G 		18 				  A  B  C  F  G  
A --> H 		8 				  A  H  
A --> I 		14 				  A  B  C  I  

In [45]:
g.dijkstra('D');

Vertex 		Distance from Source			  Path

D --> A 		9223372036854775807 				  UNREACHABLE
D --> B 		9223372036854775807 				  UNREACHABLE
D --> C 		9223372036854775807 				  UNREACHABLE
D --> D 		0 				  D  
D --> E 		9 				  D  E  
D --> F 		14 				  D  F  
D --> G 		16 				  D  G  
D --> H 		17 				  D  G  H  
D --> I 		22 				  D  G  I  

In [46]:
g.dijkstra('F');

Vertex 		Distance from Source			  Path

F --> A 		9223372036854775807 				  UNREACHABLE
F --> B 		9223372036854775807 				  UNREACHABLE
F --> C 		9223372036854775807 				  UNREACHABLE
F --> D 		9223372036854775807 				  UNREACHABLE
F --> E 		9223372036854775807 				  UNREACHABLE
F --> F 		0 				  F  
F --> G 		2 				  F  G  
F --> H 		3 				  F  G  H  
F --> I 		8 				  F  G  I  

# Reading Input File-3(UnDirected) and Creating Adjacency Matrix

In [47]:
file = open("Input_File_UnDir_2.rtf", 'r')

In [48]:
Dir_graph = 0
lines = file.readlines()
list1 = lines[0].split()
if list1[2] == 'D':
    Dir_graph = 1

In [49]:
g_size = lines[0][0].split()
print(int(lines[0][0].split()[0]))

9


In [50]:
import numpy as np

g_size = int(lines[0][0].split()[0])
g = Graph(g_size)

g.graph = np.zeros((g_size,g_size))

print(g.graph)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [51]:
if Dir_graph == 1:
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
else :
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
        g.graph[ord(j.upper())-65][ord(i.upper())-65]=val

In [52]:
print(g.graph)

[[ 0.  4.  0.  0.  0.  0.  0.  8.  0.]
 [ 4.  0.  8.  0.  0.  0.  0. 11.  0.]
 [ 0.  8.  0.  7.  0.  4.  0.  0.  2.]
 [ 0.  0.  7.  0.  9. 14.  0.  0.  0.]
 [ 0.  0.  0.  9.  0. 10.  0.  0.  0.]
 [ 0.  0.  4. 14. 10.  0.  2.  0.  0.]
 [ 0.  0.  0.  0.  0.  2.  0.  1.  6.]
 [ 8. 11.  0.  0.  0.  0.  1.  0.  7.]
 [ 0.  0.  2.  0.  0.  0.  6.  7.  0.]]


# Call Dijkstra's Algorithm from Source Node 'A', 'D', 'F'

In [53]:
g.dijkstra('A');

Vertex 		Distance from Source			  Path

A --> A 		0 				  A  
A --> B 		4 				  A  B  
A --> C 		12 				  A  B  C  
A --> D 		19 				  A  B  C  D  
A --> E 		21 				  A  H  G  F  E  
A --> F 		11 				  A  H  G  F  
A --> G 		9 				  A  H  G  
A --> H 		8 				  A  H  
A --> I 		14 				  A  B  C  I  

In [54]:
g.dijkstra('D');

Vertex 		Distance from Source			  Path

D --> A 		19 				  D  C  B  A  
D --> B 		15 				  D  C  B  
D --> C 		7 				  D  C  
D --> D 		0 				  D  
D --> E 		9 				  D  E  
D --> F 		11 				  D  C  F  
D --> G 		13 				  D  C  F  G  
D --> H 		14 				  D  C  F  G  H  
D --> I 		9 				  D  C  I  

In [55]:
g.dijkstra('F');

Vertex 		Distance from Source			  Path

F --> A 		11 				  F  G  H  A  
F --> B 		12 				  F  C  B  
F --> C 		4 				  F  C  
F --> D 		11 				  F  C  D  
F --> E 		10 				  F  E  
F --> F 		0 				  F  
F --> G 		2 				  F  G  
F --> H 		3 				  F  G  H  
F --> I 		6 				  F  C  I  

# Reading Input File-4(Directed) and Creating Adjacency Matrix

In [56]:
file = open("Input_File_Dir_3.rtf", 'r')

In [57]:
Dir_graph = 0
lines = file.readlines()
list1 = lines[0].split()
if list1[2] == 'D':
    Dir_graph = 1

In [58]:
g_size = lines[0][0].split()
print(int(lines[0][0].split()[0]))

9


In [59]:
import numpy as np

g_size = int(lines[0][0].split()[0])
g = Graph(g_size)

g.graph = np.zeros((g_size,g_size))

print(g.graph)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [60]:
if Dir_graph == 1:
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
else :
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
        g.graph[ord(j.upper())-65][ord(i.upper())-65]=val

In [61]:
print(g.graph)

[[ 0.  1.  3.  0.  0. 10.  0.  0.  0.]
 [ 0.  0.  1.  7.  5.  0.  2.  0.  0.]
 [ 0.  0.  0.  9.  3.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  2.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 12.  9.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 18.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


## Call Dijkstra's Algorithm from Source Node 'A', 'D', 'F'

In [62]:
g.dijkstra('A');

Vertex 		Distance from Source			  Path

A --> A 		0 				  A  
A --> B 		1 				  A  B  
A --> C 		2 				  A  B  C  
A --> D 		8 				  A  B  D  
A --> E 		5 				  A  B  C  E  
A --> F 		7 				  A  B  C  E  F  
A --> G 		3 				  A  B  G  
A --> H 		16 				  A  B  C  E  F  H  
A --> I 		34 				  A  B  C  E  F  H  I  

In [63]:
g.dijkstra('D');

Vertex 		Distance from Source			  Path

D --> A 		9223372036854775807 				  UNREACHABLE
D --> B 		9223372036854775807 				  UNREACHABLE
D --> C 		9223372036854775807 				  UNREACHABLE
D --> D 		0 				  D  
D --> E 		2 				  D  E  
D --> F 		1 				  D  F  
D --> G 		13 				  D  F  G  
D --> H 		10 				  D  F  H  
D --> I 		28 				  D  F  H  I  

In [64]:
g.dijkstra('F');

Vertex 		Distance from Source			  Path

F --> A 		9223372036854775807 				  UNREACHABLE
F --> B 		9223372036854775807 				  UNREACHABLE
F --> C 		9223372036854775807 				  UNREACHABLE
F --> D 		9223372036854775807 				  UNREACHABLE
F --> E 		9223372036854775807 				  UNREACHABLE
F --> F 		0 				  F  
F --> G 		12 				  F  G  
F --> H 		9 				  F  H  
F --> I 		27 				  F  H  I  

# Reading Input File-4(UnDirected) and Creating Adjacency Matrix

In [65]:
file = open("Input_File_UnDir_3.rtf", 'r')

In [66]:
Dir_graph = 0
lines = file.readlines()
list1 = lines[0].split()
if list1[2] == 'D':
    Dir_graph = 1

In [67]:
g_size = lines[0][0].split()
print(int(lines[0][0].split()[0]))

7


In [68]:
import numpy as np

g_size = int(lines[0][0].split()[0])
g = Graph(g_size)

g.graph = np.zeros((g_size,g_size))

print(g.graph)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [69]:
if Dir_graph == 1:
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
else :
    for i in range(1,len(lines)):
        line = lines[i]
        i,j,val = line.split()
        g.graph[ord(i.upper())-65][ord(j.upper())-65]=val
        g.graph[ord(j.upper())-65][ord(i.upper())-65]=val

In [70]:
print(g.graph)

[[ 0.  1.  3.  0.  0. 10.  0.]
 [ 1.  0.  1.  7.  5.  0.  2.]
 [ 3.  1.  0.  9.  3.  0.  0.]
 [ 0.  7.  9.  0.  2.  1.  0.]
 [ 0.  5.  3.  2.  0.  2.  0.]
 [10.  0.  0.  1.  2.  0.  0.]
 [ 0.  2.  0.  0.  0.  0.  0.]]


## Call Dijkstra's Algorithm from Source Node 'A', 'D', 'F'

In [71]:
g.dijkstra('A');

Vertex 		Distance from Source			  Path

A --> A 		0 				  A  
A --> B 		1 				  A  B  
A --> C 		2 				  A  B  C  
A --> D 		7 				  A  B  C  E  D  
A --> E 		5 				  A  B  C  E  
A --> F 		7 				  A  B  C  E  F  
A --> G 		3 				  A  B  G  

In [72]:
g.dijkstra('D');

Vertex 		Distance from Source			  Path

D --> A 		7 				  D  E  C  B  A  
D --> B 		6 				  D  E  C  B  
D --> C 		5 				  D  E  C  
D --> D 		0 				  D  
D --> E 		2 				  D  E  
D --> F 		1 				  D  F  
D --> G 		8 				  D  E  C  B  G  

In [73]:
g.dijkstra('F');

Vertex 		Distance from Source			  Path

F --> A 		7 				  F  E  C  B  A  
F --> B 		6 				  F  E  C  B  
F --> C 		5 				  F  E  C  
F --> D 		1 				  F  D  
F --> E 		2 				  F  E  
F --> F 		0 				  F  
F --> G 		8 				  F  E  C  B  G  